# -*- coding: utf-8 -*-
"""3_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w5uCca2r0nVTtXWPPkauD6anj0TLbU4g
"""

!ffmpeg -i 1.mp4 -vcodec libx264 2.mp4

import codecs
import base64
import ipywidgets as widgets

with codecs.open('2.mp4','rb') as f:
  d = base64.b64encode(f.read()).decode()



widgets.HTML(f'<video src="data:video/mp4;base64,{d}" controls />')

import cv2
import numpy as np
import IPython.display as dp
from google.colab.patches import cv2_imshow
import codecs
import base64
import ipywidgets as widgets

with codecs.open('2.mp4','rb') as f:
  d = base64.b64encode(f.read()).decode()


# 创建视频文件并写入帧
p1 = cv2.VideoWriter('1.mp4', cv2.VideoWriter_fourcc(*'MP4V'), 30, (300, 200))
for x in range(0, 600, 5):
    
    widgets.HTML(f'<video src="data:video/mp4;base64,{d}" controls />')
    m1 = np.full((200, 300, 3), (255,255,255), np.uint8)
    cv2.rectangle(m1, (250, 230), (120, 100), (255, 0, 0), -1)
    p1.write(m1)
   
p1.release()

# 显示原始图像
cv2_imshow(m1)

widgets.HTML(f'<video src="data:video/mp4;base64,{d}" controls />')



import cv2,time
import cv2
import numpy as np
import IPython.display as dp
from google.colab.patches import cv2_imshow
from PIL import ImageFont, ImageDraw, Image

p1=cv2.VideoCapture('1.mp4')
while p1.isOpened()==True:
  r,m=p1.read()
  if r ==True:
    cv2_imshow(m)
  else:
    break